import * as vscode from 'vscode';

const languageIDMap = {
    "abap": "ABAP",
    "bat": "Windows Bat",
    "bibtex": "BibTeX",
    "clojure": "Clojure",
    "coffeescript": "Coffeescript",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "cuda-cpp": "CUDA C++",
    "css": "CSS",
    "diff": "Diff",
    "dockerfile": "Dockerfile",
    "fsharp": "F#",
    "git-commit": "Git",
    "git-rebase": "Git",
    "go": "Go",
    "groovy": "Groovy",
    "handlebars": "Handlebars",
    "haml": "Haml",
    "html": "HTML",
    "ini": "Ini",
    "java": "Java",
    "javascript": "JavaScript",
    "javascriptreact": "JavaScript React",
    "json": "JSON",
    "jsonc": "JSON with Comments",
    "latex": "LaTeX",
    "less": "Less",
    "lua": "Lua",
    "makefile": "Makefile",
    "markdown": "Markdown",
    "objective-c": "Objective-C",
    "objective-cpp": "Objective-C++",
    "perl": "Perl",
    "perl6": "Perl",
    "php": "PHP",
    "plaintext": "Plain Text",
    "powershell": "PowerShell",
    "jade": "Pug",
    "pug": "Pug",
    "python": "Python",
    "r": "R",
    "razor": "Razor (cshtml)",
    "ruby": "Ruby",
    "rust": "Rust",
    "scss": "SCSS",
    "sass": "SASS",
    "shaderlab": "ShaderLab",
    "shellscript": "Shell Script (Bash)",
    "slim": "Slim",
    "sql": "SQL",
    "stylus": "Stylus",
    "swift": "Swift",
    "typescript": "TypeScript",
    "typescriptreact": "TypeScript React",
    "tex": "TeX",
    "vb": "Visual Basic",
    "vue": "Vue",
    "vue-html": "Vue HTML",
    "xml": "XML",
    "xsl": "XSL",
    "yaml": "YAML",
} as const;

export const getCurrentFileLanguage = () => {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
        return;
    }
    const languageID = editor.document.languageId as keyof typeof languageIDMap;
    return languageIDMap[languageID];
};